<?php


namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComponentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $components = [
            // COMPONENTES HARRIS

            // Componentes do CONJUNTO RÁDIO (RF-7800V-P)
            [
                'name' => 'ADAPTADOR DE DADOS / EB 11 - MARCA: HARRIS; MODELO: 12067-5600-01; ADAPTADOR DE DADOS REMOTO PARA USB, TIPO "A", COM 32 PINOS.',
                'category_id' => 33,
                'code_number' => '0020306024',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Adaptador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'ANTENA / EB 11 - MARCA: HARRIS; MODELO: 12011-2600-01; FAIXA DE FREQUÊNCIA: 30 A 108 MHZ; ANTENA WHIP (CURTA).',
                'category_id' => 33,
                'code_number' => '0020306027',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena Whip',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'ANTENA / EB 11 - MARCA: HARRIS; MODELO: 12011-2700-01; 20M; MB HH; FAIXA DE FREQUÊNCIA: 30 A 108 MHZ; ANTENA BLADE (FLEXÍVEL).',
                'category_id' => 33,
                'code_number' => '0020306026',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena Blade',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'ANTENA / EB 11 - MARCA: HARRIS; MODELO: 12041-6550-01; ANTENA SOLIDÁRIA AO RECEPTOR TRANSMISSOR, TAMANHO: 3,5 CM.',
                'category_id' => 33,
                'code_number' => '0020306025',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena Solidária',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BATERIA RECARREGÁVEL / DE LI-ION 12041-2100-01; FABRICANTE: HARRIS; PN: 12041-2100-01.',
                'category_id' => 33,
                'code_number' => '120376',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CD DE INSTALAÇÃO / EB 11 - MARCA: HARRIS; MODELO: RF-7800VH-SW001; PN: 10518-2930-05; CD DE INSTALAÇÃO COM O SOFTWARE DE PROGRAMAÇÃO DO CONJUNTO RÁDIO.',
                'category_id' => 33,
                'code_number' => '0020306030',
                'quantity' => 1,
                'serial_number' => 'CD de Instalação',
                'loan_name' => '',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DE CONSULTA RÁPIDA / EB 11 - MARCA: HARRIS; MODELO: RF-7800V-HH; PN: 10515-0363-4100; GUIA DE CONSULTA RÁPIDA COM AS PRINCIPAIS FUNÇÕES DO CONJUNTO RÁDIO.',
                'category_id' => 33,
                'code_number' => '0020306029',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia de Consulta Rápida',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'PORTA RÁDIO CAMUFLADO / EB 11 - MARCA: HARRIS; MODELO: FALCOM III - RF7800V-P; BOLSA PARA TRANSPORTE DO RÁDIO PORTÁTIL.',
                'category_id' => 33,
                'code_number' => '0020306023',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Porta Rádio',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],

            // Componentes do CONJUNTO RÁDIO (MPR-9600-MP)
            [
                'name' => 'ADAPTER ASSEMBLY (10372-1260-01) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO RÁDIO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304349',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Adapter Assembly',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'ASYNC DATA CABLE (10535-0775-A006) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304358',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Dados',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BATTERY BOX, WIDE (10513-4800-08) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304350',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Caixa da Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'BATTERY LITHION-ION - MÉXICO (B41-0100-001) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO MPR 9600.',
                'category_id' => 40,
                'code_number' => '0020304366',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Bateria Lithion-Ion',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'FALCON II BACKPACK (RF-5930-CA0001) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO MPR 9600.',
                'category_id' => 40,
                'code_number' => '0020304365',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Mochila de Transporte',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'GPS ANTENNA KIT (10511-0400-01) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO RÁDIO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304346',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Kit Antena GPS',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'GROUND STAKE KIT (10303-1008-01) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO RÁDIO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304345',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Estaca de Aterramento',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'HANDSET, MODIFIED H-250 (10075-1399) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304355',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'PTT',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'HF PORTABLE ANTENNA, 2 TO 30MHZ (RF-1941) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304364',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena Portátil',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'HF RADIO PROGRAM APPL (RF-6550H) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304361',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Software de Programação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'OE-505 WHIP ANTENNA KIT (10372-0240-02) / CONFORME MANUAL, CONSTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304351',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Kit Antena Whip',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'OPERATION MANUAL (10515-0228-4200) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304352',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Manual de Operação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'TACTICAL CHAT (RF-6551H) / CONFORME MANUAL, CONTANTE NA FIGURA 2-1 DO MPR-9600.',
                'category_id' => 40,
                'code_number' => '0020304363',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Tactical Chat',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],

            // Componentes do CONJUNTO RÁDIO (PRC 910)
            /*[
                'name' => 'ANTENA VERTICAL / ANTENA CHICOTE LONGA DE 103 CM EB 11 - (AT- 988).',
                'category_id' => null,
                'code_number' => '143001',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'ANTENA WHIP / EB 14-AN 83; PN: HAD4006.',
                'category_id' => null,
                'code_number' => '128186',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'BASE DE ANTENA / EB 11 - (EA 33).',
                'category_id' => null,
                'code_number' => '143000',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'BATERIA LI-ION / EB 11 - TLI-714.',
                'category_id' => null,
                'code_number' => '141567',
                'quantity' => 3,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'COMBINADO TELEFÔNICO / EB 11 - (H-250-U).',
                'category_id' => null,
                'code_number' => '147509',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'FOLHETO OPERADOR / DO RT 910; MODELO: OPERATOR LEAFLET RT 910.',
                'category_id' => null,
                'code_number' => '139335',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'FONE OUVIDO EB 11 HS -624 / EB 11 HS -624.',
                'category_id' => null,
                'code_number' => '0020303291',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'MANUAL DE MANUTENÇÃO / E OPERAÇÃO DE 1º E 2º ESCALÕES DO CONJUNTO RÁDIO EB 11 - PRC 910.',
                'category_id' => null,
                'code_number' => '141230',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'MOCHILA PARA RÁDIO / EB 11 - (ST - 710).',
                'category_id' => null,
                'code_number' => '147624',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],
            [
                'name' => 'RECEPTOR-TRANSMISSOR / EB 11 - RT-910.',
                'category_id' => null,
                'code_number' => '143182',
                'quantity' => 1,
                'serial_number' => 'np',
                'created_at' =>$now,
               'updated_at' => $now,
'show_on_loan' => true,
            ],*/


            // COMPONENTES MOTOROLA

            // Componentes do ESTAÇÃO REPETIDORA (GTR8000)
            [
                'name' => 'ANTENA FIXA PARA ESTAÇÃO REPETIDORA MOTOROLA - GTR 8000',
                'category_id' => 2,
                'code_number' => 'DSSC420HF1LDF',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CABO COAXIAL',
                'category_id' => 2,
                'code_number' => 'C400F-NMNM-10M',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo Coaxial',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ALIMENTAÇÃO',
                'category_id' => 2,
                'code_number' => 'NP',
                'quantity' => 6,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Alimentação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ATERRAMENTO',
                'category_id' => 2,
                'code_number' => 'NP',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Aterramento',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE REDE BLINDADO; CAT. 5E COM 50 CENTÍMETROS',
                'category_id' => 2,
                'code_number' => 'NP',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Rede Blindado',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DE INSTALAÇÃO',
                'category_id' => 2,
                'code_number' => 'NP',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia de Instalação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MOTOROLA PIDU PLUS',
                'category_id' => 2,
                'code_number' => 'WB3177A',
                'quantity' => 1,
                'serial_number' => '1051570812',
                'loan_name' => 'PIDU',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MOTOROLA PTP - LPU (CAIXA PROTEÇÃO CONTRA RAIOS)',
                'category_id' => 2,
                'code_number' => 'WB2907B',
                'quantity' => 1,
                'serial_number' => 'S20110266114',
                'loan_name' => 'Motorola PTP - LPU',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MOTOROLA PTP 49600',
                'category_id' => 2,
                'code_number' => 'WB3225AA',
                'quantity' => 1,
                'serial_number' => '224JMC0621',
                'loan_name' => 'Motorola PTP 49600',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'SUPORTE DE FIXAÇÃO',
                'category_id' => 2,
                'code_number' => 'NP',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Suporte de Fixação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],

            // Componentes do RECEPTOR E TRANSMISSOR (XTS2500 ST Modelo II)
            [
                'name' => 'ANTENA',
                'category_id' => 6,
                'code_number' => 'NAF5037A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BATERIA',
                'category_id' => 6,
                'code_number' => 'NNTN7554A',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ALIMENTAÇÃO',
                'category_id' => 6,
                'code_number' => 'NP',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Fonte de Alimentação Carregador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CARREGADOR BATERIA',
                'category_id' => 6,
                'code_number' => 'WPLN4114AR',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Carregador de Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CARTÃO DE REFERÊNCIA RÁPIDA',
                'category_id' => 6,
                'code_number' => 'PMLN4940F-1',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cartão de Referência Rápida',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CLIPE DE CINTO',
                'category_id' => 6,
                'code_number' => 'HLN6853A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Clipe de Cinto',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'COMBINADO DE MÃO',
                'category_id' => 6,
                'code_number' => 'PMMN4038A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'PTT',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'FOLHETO OPERADOR',
                'category_id' => 6,
                'code_number' => 'NNTN7223A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Folheto Operador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DO USUÁRIO',
                'category_id' => 6,
                'code_number' => 'NP',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia do Usuário',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MANUAL',
                'category_id' => 6,
                'code_number' => '68P02300U90-O',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Manual',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'PROTETOR ACRÍLICO',
                'category_id' => 6,
                'code_number' => 'I5-05579Z',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Protetor Lateral',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'SOFTWARE DE PROGRAMAÇÃO',
                'category_id' => 6,
                'code_number' => 'NVN5314B',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Software de Programação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'SUPORTE ACRÍLICO',
                'category_id' => 6,
                'code_number' => '4385665D01',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Suporte Acrílico',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],

            // Componentes do CONJUNTO RÁDIO (XTL2200)
            [
                'name' => 'ANTENA',
                'category_id' => 4,
                'code_number' => 'HAF4016A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'AUTO-FALANTE',
                'category_id' => 4,
                'code_number' => 'HSN4031B',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Auto Falante',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BASE DE MONTAGEM',
                'category_id' => 4,
                'code_number' => 'HLN6861C',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Base de Montagem',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ALIMENTAÇÃO',
                'category_id' => 4,
                'code_number' => 'HKN4191B',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Alimentação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE DADOS',
                'category_id' => 4,
                'code_number' => 'HLN6160B',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de dados',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CARTÃO DE REFERÊNCIA RÁPIDA',
                'category_id' => 4,
                'code_number' => '681585H01-T1',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cartão de Referência Rápida',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CHAVE',
                'category_id' => 4,
                'code_number' => 'HLN6970A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Chave',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'FOLHETO OPERADOR',
                'category_id' => 4,
                'code_number' => '68P80310B27-O',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Folheto Operador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DO USUÁRIO',
                'category_id' => 4,
                'code_number' => 'NNTN7930D',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia do Usuário',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MICROFONE MÃO',
                'category_id' => 4,
                'code_number' => 'HMN1090C',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'PTT',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'SOFTWARE DE PROGRAMAÇÃO',
                'category_id' => 4,
                'code_number' => 'NVN5314B',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Software de Programação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'SUPORTE PARA COMBINADO',
                'category_id' => 4,
                'code_number' => 'NP',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Suporte para Combinado',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],

            // Componentes do CONJUNTO RÁDIO (APX2000 Modelo III)
            [
                'name' => 'ANTENA',
                'category_id' => 7,
                'code_number' => 'NAF5085A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BATERIA',
                'category_id' => 7,
                'code_number' => 'NNTN8128BR',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CARREGADOR BATERIA',
                'category_id' => 7,
                'code_number' => 'WPLN4243A',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Carregador de Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'PROTETOR ACRÍLICO',
                'category_id' => 7,
                'code_number' => '15012142001',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Protetor Lateral',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE PROGRAMAÇÃO',
                'category_id' => 7,
                'code_number' => 'PMKN4013C',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Programação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],

            // Componentes do CONJUNTO RÁDIO (XTL1500)
            [
                'name' => 'ANTENA / EB 14 - MARCA: MOTOROLA; MODELO RRA4976B',
                'category_id' => 3,
                'code_number' => '0020304485',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BASE DE MONTAGEM / UTILIZADA PARA FIXAÇÃO DO EQUIPAMENTO EM VEÍCULOS.',
                'category_id' => 3,
                'code_number' => '0020304480',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Base de Montagem',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ALIMENTAÇÃO / COMPOSTO POR UM PARTE DE FIOS, PRETO E VERMELHO, EM UMA EXTREMIDADE O CONECTOR DE ENCAIXE NO RÁDIO E NA OUTRA OS BORNES PARA FIXAÇÃO NA FONTE DE ALIMENTAÇÃO. NO MEIO DO FIO VERMELHO ESTÁ O SUPORTE PARA O FUSÍVEL',
                'category_id' => 3,
                'code_number' => '0020304484',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Alimentação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ATERRAMENTO / EB 14 - MARCA: MOTOROLA; UTILIZADO PARA REALIZAR A LIGAÇÃO DO CONJUNTO RÁDIO EM UM SISTEMA DE ATERRAMENTO.',
                'category_id' => 3,
                'code_number' => '0020304483',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Aterramento',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CABO DE DADOS / EB 14 - MARCA: MOTOROLA; MODELO HLN6863B',
                'category_id' => 3,
                'code_number' => '0020304486',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Dados',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CARTÃO DE REFERÊNCIA RÁPIDA / EB 14 - MARCA: MOTOROLA; MODELOS 681585H01-T1, 681585H01-T2 E 681585H01-T3; CARTÃO DE REFERÊNCIA RÁPIDA.',
                'category_id' => 3,
                'code_number' => '0020304490',
                'quantity' => 3,
                'serial_number' => 'NP',
                'loan_name' => 'Cartão de Referência Rápida',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'COMBINADO / ACESSÓRIO UTILIZADO NA TRANSMISSÃO DO SINAL PELA VOZ DO OPERADOR.',
                'category_id' => 3,
                'code_number' => '0020304481',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'PTT',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'FOLHETO OPERADOR / FOLHETO DE INSTRUÇÃO DA ANTENA MÓVEL COM BASE VEICULAR - MOTOROLA, MODELO 68P80310B27-O',
                'category_id' => 3,
                'code_number' => '0020304487',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Folheto Operador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'FOLHETO OPERADOR / FOLHETO DE NORMAS DE SEGURANÇA E DE EXPOSIÇÃO À ENERGIA DE RF QUANDO DA UTILIZAÇÃO DE RÁDIOS BIDIRECIONAIS MÓVEIS INSTALADOS EM VEÍCULOS OU ESTAÇÕES DE CONTROLE EM INSTALAÇÕES FIXAS - MOTOROLA, MODELO 68P81095C99-E.',
                'category_id' => 3,
                'code_number' => '0020304488',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'FOLHETO OPERADOR / FOLHETO DE NORMAS DE SEGURANÇA',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DO USUÁRIO / GUIA DO USUÁRIO EM "CD" - MANUAL DE OPERAÇÃO, MOTOROLA ASTRO - XTL 1500; MODELO 6815852H01-T',
                'category_id' => 3,
                'code_number' => '0020304489',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia do Usuário',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'SOFTWARE DE PROGRAMAÇÃO / EB 14 - MARCA: MOTOROLA; GERENTE DE LIGAÇÃO DE DADOS EM "CD" - SOFTWARE DE PROGRAMAÇÃO, VERSÃO R01.01.00, MODELO NVN5314B',
                'category_id' => 3,
                'code_number' => '0020304532',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Software de Programação',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'SUPORTE PARA COMBINADO / EB 14 - MARCA: MOTOROLA; SUPORTE METÁLICO UTILIZADO PARA FIXAÇÃO DO COMBINADO DE MÃO EM ESTRUTURA FIXA, EVITANDO QUEDA.',
                'category_id' => 3,
                'code_number' => '0020304482',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Suporte para Combinado',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],

            // Componentes do CONJUNTO RÁDIO (XTS1500 Modelo I)
            [
                'name' => 'ANTENA / ANTENA FLEXÍVEL MOTOROLA, MODELO NAF5037A',
                'category_id' => 5,
                'code_number' => '0020304492',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Antena',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'BATERIA / EB 14 - MARCA: MOTOROLA; MODELO NTN9858C; BATERIA NÍQUEL-METAL HIDRETO (NI-MH) MOTOROLA, 7,2 VCC',
                'category_id' => 5,
                'code_number' => '0020304495',
                'quantity' => 2,
                'serial_number' => 'NP',
                'loan_name' => 'Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'CABO DE ALIMENTAÇÃO / CABO PARA ALIMENTAÇÃO EM ENERGIA ELÉTRICA PARA CORRENTE ALTERNADA.',
                'category_id' => 5,
                'code_number' => '0020304476',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cabo de Alimentação Carregador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CARREGADOR BATERIA / EB 14 - MARCA: MOTOROLA; MODELO WPLN4114AR, CARREGADOR DE BATERIA MOTOROLA IMPRES, 110 VCA',
                'category_id' => 5,
                'code_number' => '0020304497',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Carregador de Bateria',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CARTÃO DE REFERÊNCIA RÁPIDA / EB 14 - MARCA: MOTOROLA; MODELOS PMLN4940F-1 ATÉ PMLN4940F-13; CARTÃO DE REFERÊNCIA RÁPIDA',
                'category_id' => 5,
                'code_number' => '0020304501',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Cartão de Referência Rápida',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'CLIPE DE CINTO / EB 14 - MARCA: MOTOROLA; MODELO HLN6853A; CLIPE DE CINTO',
                'category_id' => 5,
                'code_number' => '0020304496',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Clipe de Cinto',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
            [
                'name' => 'FOLHETO OPERADOR / FOLHETO DE NORMAS DE SEGURANÇA DE EXPOSIÇÃO À ENERGIA DE RF QUANDO DO USO DE RÁDIOS PORTÁTEIS BIDIRECIONAIS - MOTOROLA, MODELO NNTN7223A - 6881095C98-D',
                'category_id' => 5,
                'code_number' => '0020304502',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Folheto Operador',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DO USUÁRIO / GUIA DO USUÁRIO - CARREGADOR DE BATERIA MOTOROLA IMPRES, MODELO WPLN4114AR',
                'category_id' => 5,
                'code_number' => '0020304498',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Guia do Usuário',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'GUIA DO USUÁRIO / GUIA DO USUÁRIO EM "CD" - MANUAL DE OPERAÇÃO, MOTOROLA ASTRO; MODELO PMLN4940F',
                'category_id' => 5,
                'code_number' => '0020304500',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'GUIA DO USUÁRIO EM "CD"',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'MANUAL / MANUAL DE MANUTENÇÃO DA BATERIA, MOTOROLA, MODELO 68P02300U90-O',
                'category_id' => 5,
                'code_number' => '0020304499',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Manual',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => false,
            ],
            [
                'name' => 'PROTETOR ACRÍLICO / EB 14 - MARCA: MOTOROLA; MODELO I5-05579Z; PROTETOR ACRÍLICO LATERAL DO CONECTOR DE PROGRAMAÇÃO',
                'category_id' => 5,
                'code_number' => '0020304493',
                'quantity' => 1,
                'serial_number' => 'NP',
                'loan_name' => 'Protetor Lateral',
                'created_at' => $now,
                'updated_at' => $now,
                'show_on_loan' => true,
            ],
        ];

        DB::table('components')->insert($components);
    }
}
