<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HarisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Definir a data atual para created_at e updated_at
        $now = Carbon::now();

        // Dados a serem inseridos
        $materials = [
            //FALCON III E BASE VEICULAR
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055317',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A09001',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055321',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A09042',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055322',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A08509',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055323',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A09825',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055325',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A08466',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055326',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A08985',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055811',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A10233',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055812',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A10112',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055813',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A09018',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06046',
                'patrimony_number' => '100203000055814',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-P;',
                'serial_number' => 'A10215',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000055311',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'A09868',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000055312',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V ;',
                'serial_number' => 'A09756',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000055313',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V ;',
                'serial_number' => 'A09675',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000055314',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V ;',
                'serial_number' => 'A09754',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000055315',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'A09866',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // FALCONS QUE ENTRARAM POR ÚLTIMO EM CARGA
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060400',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'H39925',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060401',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'H40101',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060402',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'H40165',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060403',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V;',
                'serial_number' => 'H39956',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // FALCON MULTIBANDA (MB)
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060404',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V MB;',
                'serial_number' => 'H27878',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 39,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060405',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V MB;',
                'serial_number' => 'H27942',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 39,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060406',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V MB;',
                'serial_number' => 'H28106',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 39,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06071',
                'patrimony_number' => '100203000060407',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30-108MHz; Sistema: EB11; Fornecedor: Harris; Número de Referência: RF-7800V-V MB;',
                'serial_number' => 'H27924',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 39,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BASE VEICULAR FALCON III
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BASE VEICULAR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BASE VEICULAR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BASE VEICULAR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BASE VEICULAR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BASE VEICULAR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BATERIAS FALCON III 
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'BATERIA FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // CARREGADOR FALCON III
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // CABO DE DADOS FALCON III 
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CABO DE DADOS FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ADAPTADOR USB FALCON III
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR USB FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],


            // ADAPTADOR VISOR FALCON III
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR "VISOR" FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 38,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR "VISOR" FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 38,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'ADAPTADOR "VISOR" FALCON III',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 38,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* TADIRAN
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024396',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1503',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024397',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1341',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024398',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1718',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024400',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1182',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024401',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1443',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024402',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1158',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024404',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1244',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024405',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1669',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024406',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1124',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06134',
                'patrimony_number' => '100203000024407',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (VHF); 30¿87,975MHz; Sistema: EB11; Fornecedor: Tadiran; Número de Referência: PRC 910;',
                'serial_number' => '1077',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 50,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06147',
                'patrimony_number' => '100203000050816',
                'name' => 'BATTERY,STORAGE / FABRICANTE: TADIRAN; MODELO: NTN9568A',
                'serial_number' => 'A7471014',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 51,  
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06147',
                'patrimony_number' => '100203000050818',
                'name' => 'BATTERY,STORAGE / FABRICANTE: TADIRAN; MODELO: NTN9568A',
                'serial_number' => 'A7471018',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 51, 
                'created_at' => $now,
                'updated_at' => $now,
            ],*/


            // FALCON II
            [
                'record_number' => '06148',
                'patrimony_number' => '100203000050819',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (HF); 1,6-30MHz; Sistema: Não se aplica; Fornecedor: Harris; Número de Referência: MPR-9600-MP;',
                'serial_number' => 'B00606',
                'status' => 'Disponível',
                'categories_id' => 40,
                'images' => '[]',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06148',
                'patrimony_number' => '100203000050822',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (HF); 1,6-30MHz; Sistema: Não se aplica; Fornecedor: Harris; Número de Referência: MPR-9600-MP;',
                'serial_number' => 'C1002',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06148',
                'patrimony_number' => '100203000050825',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (HF); 1,6-30MHz; Sistema: Não se aplica; Fornecedor: Harris; Número de Referência: MPR-9600-MP;',
                'serial_number' => 'C1018',
                'status' => 'Disponível',
                'categories_id' => 40,
                'images' => '[]',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06148',
                'patrimony_number' => '100203000050827',
                'name' => 'CONJUNTO RÁDIO / Faixa de Frequência: (HF); 1,6-30MHz; Sistema: Não se aplica; Fornecedor: Harris; Número de Referência: MPR-9600-MP;',
                'serial_number' => 'C1033',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // CARREGADOR FALCON II
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON II',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 41,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON II',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 41,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'CARREGADOR FALCON II',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 41,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // PTT FALCON
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'PTT FALCON',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* COMPONENTE DE MANUTENÇÃO
            [
                'record_number' => '06159',
                'patrimony_number' => '100203000055340',
                'name' => 'COMPONENTE PARA MANUTENÇÃO / Número de Referência: 91931164; Finalidade: Não Informado; Tipo: Anel;',
                'serial_number' => 'UCC22514712',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 57, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06159',
                'patrimony_number' => '100203000055341',
                'name' => 'COMPONENTE PARA MANUTENÇÃO / Número de Referência: 91931164; Finalidade: Não Informado; Tipo: Anel;',
                'serial_number' => 'UCC22514714',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 57, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06159',
                'patrimony_number' => '100203000055342',
                'name' => 'COMPONENTE PARA MANUTENÇÃO / Número de Referência: 91931164; Finalidade: Não Informado; Tipo: Anel;',
                'serial_number' => 'UCC22514717',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 57, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06159',
                'patrimony_number' => '100203000055828',
                'name' => 'COMPONENTE PARA MANUTENÇÃO / Número de Referência: 91931164; Finalidade: Não Informado; Tipo: Anel;',
                'serial_number' => 'UCC22515076',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 57, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => '06159',
                'patrimony_number' => '100203000055829',
                'name' => 'COMPONENTE PARA MANUTENÇÃO / Número de Referência: 91931164; Finalidade: Não Informado; Tipo: Anel;',
                'serial_number' => 'UCC22515130',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 57, 
                'created_at' => $now,
                'updated_at' => $now,
            ],*/

            //FONTES DE ALIMENTAÇÃO 
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'FONTE DE ALIMENTAÇÃO YAESU',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 43,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'FONTE DE ALIMENTAÇÃO YAESU',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 43,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'FONTE DE ALIMENTAÇÃO YAESU',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 43,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'record_number' => 'NP',
                'patrimony_number' => 'NP',
                'name' => 'FONTE DE ALIMENTAÇÃO',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 44,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // CASE TIPO BAÚ
            [
                'record_number' => '34040',
                'patrimony_number' => '100203000055841',
                'name' => 'CASE TIPO BAU / 80X50X50 CM',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 31,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'record_number' => '34040',
                'patrimony_number' => '100203000055841',
                'name' => 'CASE TIPO BAU / 80X50X50 CM',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'categories_id' => 31,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Inserir os dados na tabela
        DB::table('materials')->insert($materials);
    }
}
