<?php

namespace Database\Seeders;

use App\Models\Material;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LongLastingMaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $items = [
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306303',
                'name' => 'COMBINADO REMOTO COM ADAPTADOR DE RF / -',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306105',
                'name' => 'COMBINADO DE TEMPORAS / PARA RÁDIOS XTS',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306105',
                'name' => 'COMBINADO DE TEMPORAS / PARA RÁDIOS XTS',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306105',
                'name' => 'COMBINADO DE TEMPORAS / PARA RÁDIOS XTS',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '160289',
                'name' => 'ALTO-FALANTE / Alimentação: Não Informado; Tipo: Externo; Resistente a Água: Não Informado; Número de Referência: MA 4988 B; B791174; WE128B; 791174; Potência: 20W;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '160289',
                'name' => 'ALTO-FALANTE / Alimentação: Não Informado; Tipo: Externo; Resistente a Água: Não Informado; Número de Referência: MA 4988 B; B791174; WE128B; 791174; Potência: 20W;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '160289',
                'name' => 'ALTO-FALANTE / Alimentação: Não Informado; Tipo: Externo; Resistente a Água: Não Informado; Número de Referência: MA 4988 B; B791174; WE128B; 791174; Potência: 20W;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '160289',
                'name' => 'ALTO-FALANTE / Alimentação: Não Informado; Tipo: Externo; Resistente a Água: Não Informado; Número de Referência: MA 4988 B; B791174; WE128B; 791174; Potência: 20W;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '160289',
                'name' => 'ALTO-FALANTE / Alimentação: Não Informado; Tipo: Externo; Resistente a Água: Não Informado; Número de Referência: MA 4988 B; B791174; WE128B; 791174; Potência: 20W;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306295',
                'name' => 'MICROFONE DE MESA / PARA RÁDIOS XTL',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306295',
                'name' => 'MICROFONE DE MESA / PARA RÁDIOS XTL',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306295',
                'name' => 'MICROFONE DE MESA / PARA RÁDIOS XTL',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306295',
                'name' => 'MICROFONE DE MESA / PARA RÁDIOS XTL',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '0020306295',
                'name' => 'MICROFONE DE MESA / PARA RÁDIOS XTL',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '163046',
                'name' => 'ANTENA / Faixa de Frequência: (UHF): 806-870MHz; Ganho: Não Informado; Polarização: Não Informado; Tipo: Não Informado; Número de Referência: NAF5042; Potência Máxima: Não Informado;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '163046',
                'name' => 'ANTENA / Faixa de Frequência: (UHF): 806-870MHz; Ganho: Não Informado; Polarização: Não Informado; Tipo: Não Informado; Número de Referência: NAF5042; Potência Máxima: Não Informado;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patrimony_number' => '163046',
                'name' => 'ANTENA / Faixa de Frequência: (UHF): 806-870MHz; Ganho: Não Informado; Polarização: Não Informado; Tipo: Não Informado; Número de Referência: NAF5042; Potência Máxima: Não Informado;',
                'serial_number' => 'NP',
                'status' => 'Disponível',
                'images' => '[]',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($items as $item) {
            Material::create($item);
        }
    }
}
